In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data='Merhaba'
data[0]

'M'

In [ ]:
data[-1]

'a'

In [ ]:
len(data)

7

In [ ]:
a,b,c=1,2,-10

In [ ]:
print(a,b,c)

1 2 -10


In [ ]:
notum=90

if notum>90:
  print("AA")
elif notum>80:
  print("BA")
else:
  print("KALDINIZ")

BA


In [ ]:
for i in range (1,10,2): #1 dene 10a kadar 10 dahıl değil
  print(i)

1
3
5
7
9


In [ ]:
i=0
while i<10: #0 10 kadar 10 dahil değil
  print(i)
  i=i+1

0
1
2
3
4
5
6
7
8
9


TUPLE,LİSTE,SÖZLÜK

In [ ]:
a=(10,20,3.14)

In [ ]:
a[1]

20

In [ ]:
a[5] # 5 diye indeks olmadından hata verir

IndexError: tuple index out of range

In [ ]:
a[1]=100 # tuple değiştirilemez

TypeError: 'tuple' object does not support item assignment

In [ ]:
a.append(100) # tuppelda append metodu yok

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
liste=[10,100,3.14,'ERZURUM',True]

In [ ]:
liste

[10, 100, 3.14, 'ERZURUM', True]

In [ ]:
liste[1]

100

In [ ]:
liste[1]=-25

In [ ]:
liste

[10, -25, 3.14, 'ERZURUM', True]

In [ ]:
liste.append(15000) # sona ekler

In [ ]:
liste

[10, -25, 3.14, 'ERZURUM', True, 15000]

In [ ]:
liste.pop() #pop sonda ki değeri gertirir

15000

In [ ]:
sozluk={'erzurum':25,'ankara':6,'trabzon':61}

In [ ]:
print('Erzurum değeri %d'%sozluk['erzurum'])

Erzurum değeri 25


In [ ]:
sozluk['trabzon']

61

In [ ]:
sozluk['trabzon']=100

In [ ]:
sozluk

{'erzurum': 25, 'ankara': 6, 'trabzon': 100}

In [ ]:
sozluk.keys()

dict_keys(['erzurum', 'ankara', 'trabzon'])

In [ ]:
sozluk.values()

dict_values([25, 6, 100])

In [ ]:
for i in sozluk.keys():
  print(i)

erzurum
ankara
trabzon


In [ ]:
for i in sozluk.keys():
  print(sozluk[i])

25
6
100


FONKSİYON

In [ ]:
def toplam(a,b):
  return a+b

toplam(10,20)

30

In [ ]:

def fonksiyon():
  x=(1,2,3)
  return x
a,b,c=fonksiyon()
print(a,b,c)

1 2 3


In [ ]:
a=5
x=a**2
print(x)

25


In [ ]:
toplam1=lambda x:x**2
print(toplam1(5))

25


In [ ]:
liste=[1,2,3]
y=map(lambda x:x**2,liste)
print(list(y))

[1, 4, 9]


In [ ]:
liste1=[1,2,3,4]
liste2=[4,5,6,10]
x=zip(liste1,liste2) # iki listeyi birleştirir
değer=list(x)
print(değer)


[(1, 4), (2, 5), (3, 6), (4, 10)]


In [ ]:
list(zip(*değer)) # zzip ile eşleştirilenleri ayırır

[(1, 2, 3, 4), (4, 5, 6, 10)]

# **NUMPY KÜTÜPHANESİ**

In [ ]:
import numpy as np

In [ ]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])


In [ ]:
array.shape

(15,)

In [ ]:
a=array.reshape(3,5) # yenıden şekıllendırmeyı sağlar tam bolunmesı azım ayarlanmalı dikkat
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
a.shape

(3, 5)

In [ ]:
a.ndim #boyut sayısı veriyo

2

In [ ]:
a.dtype.name

'int64'

In [ ]:
a.size

15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
array1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
sıfır=np.zeros((3,4))

In [ ]:
sıfır

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
sıfır[0,0]=100
sıfır

array([[100.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [ ]:
birler=np.ones((3,4))
birler

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
birler[0,1]=1000
birler

array([[   1., 1000.,    1.,    1.],
       [   1.,    1.,    1.,    1.],
       [   1.,    1.,    1.,    1.]])

In [ ]:
a=np.arange(10,100,5)#10oluyo ve 100 olmuyo
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
a=np.linspace(10,100,19) # 10 ve 100 oluyo 20 eşit parçaya boluyo
a

array([ 10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,  60.,
        65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [ ]:
a-b

array([-3, -3, -3])

In [ ]:
a**2

array([1, 4, 9])

In [ ]:
b=np.sin(a)
b

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
b<0.6

array([False, False,  True])

In [ ]:
a=np.random.random((5,5))#0-1 arasaı random uretıyo
a

array([[0.08537782, 0.68525111, 0.13759038, 0.19363339, 0.37304518],
       [0.60411679, 0.85734934, 0.80209323, 0.39382832, 0.76660598],
       [0.85289111, 0.48979542, 0.78087919, 0.42761136, 0.62477483],
       [0.30627503, 0.90929772, 0.46886904, 0.54865414, 0.56723081],
       [0.53139856, 0.3487409 , 0.16231813, 0.4188242 , 0.12091095]])

In [ ]:
a=np.random.randn(5)#-ve +değerler random atıyo
a

array([-4.41943504e-01, -1.74057987e-01,  2.46941768e-04,  1.60130786e-02,
       -5.27563166e-01])

In [ ]:
a=np.array([[1,4],[2,5],[3,6]])
a

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
b=np.transpose(a)#satırı sutun sutunu satır yapıyo
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.random.random((5,5))#0-1 arasaı random uretıyo
a

array([[0.11947455, 0.88258899, 0.99708856, 0.13864121, 0.91450105],
       [0.80708362, 0.93200389, 0.79765088, 0.84788796, 0.6723168 ],
       [0.48739408, 0.7388549 , 0.86010417, 0.69263415, 0.02512211],
       [0.90342647, 0.30642448, 0.58387917, 0.91526556, 0.02287839],
       [0.60601098, 0.41605274, 0.77156147, 0.15106821, 0.16201957]])

In [ ]:
toplam=np.sum(a)
toplam

np.float64(14.751933930810791)

In [ ]:
maximum=np.max(a)
maximum


np.float64(0.9970885558269237)

In [ ]:
a.sum(axis=0) #sütün toplamı

array([2.92338969, 3.27592499, 4.01028425, 2.74549709, 1.79683792])

In [ ]:
a.sum(axis=1) #satır toplamı

array([3.05229435, 4.05694314, 2.80410941, 2.73187407, 2.10671296])

In [ ]:
np.sqrt(a)


array([[0.3456509 , 0.93946207, 0.99854322, 0.37234555, 0.95629548],
       [0.89837833, 0.96540349, 0.89311303, 0.92080832, 0.81994927],
       [0.69813614, 0.85956669, 0.92741801, 0.83224645, 0.15849955],
       [0.95048749, 0.55355621, 0.76411987, 0.95669512, 0.15125603],
       [0.77846707, 0.6450215 , 0.87838572, 0.38867494, 0.40251655]])

In [ ]:
a=np.array([1,2,9])
b=np.array([4,5,6])
c=np.concatenate([a,b])#yan yana bırlestırme yapıyo
c

array([1, 2, 9, 4, 5, 6])

In [ ]:
c[2:]

array([9, 4, 5, 6])

In [ ]:
c[::]

array([1, 2, 9, 4, 5, 6])

In [ ]:
c[::-1] #numoy dökumantsyanuna bakın dedı

array([6, 5, 4, 9, 2, 1])